# Generated by Django 5.1 on 2024-09-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coupon', '0001_initial'),
        ('Products', '0001_initial'),
        ('customerSection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Full Payment', 'Full Payment')], default='Full Payment', max_length=50)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Processing', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_partial_cod_remain_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partial_cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('for_order_confirmation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_applied', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coupon.coupon')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerSection.customershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
