# Generated by Django 4.0.3 on 2024-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_paid_amount_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
