# Generated by Django 5.1 on 2024-09-11 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', ckeditor.fields.RichTextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('message_type', models.CharField(choices=[('Welcome for registration', 'Welcome Message'), ('Password change success', 'Password change success Message'), ('Send password reset link', 'Send password reset link Message'), ('Password reset success', 'password reset success Message'), ('Payment success and order confirmation', 'Payment success and order confirmation Message'), ('Payment failure and order saved', 'Payment failure and order saved Message'), ('Payment success and order confirmation for Owner', 'Payment success and order confirmation for Owner Message')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
    ]
