# Generated by Django 5.1 on 2024-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='message_type',
            field=models.CharField(choices=[('Welcome for registration', 'Welcome Message'), ('Password change success', 'Password change success Message'), ('Send password reset link', 'Send password reset link Message'), ('password reset success', 'password reset success Message'), ('Payment success and order confirmation', 'Payment success and order confirmation Message'), ('Payment failure and order saved', 'Payment failure and order saved Message')], max_length=255),
        ),
    ]
